fora/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'^forums/', include('forums.urls', namespace='forums')),
    url(r'^threads/', include('threads.urls', namespace='threads')),
    url(r'^users/', include('users.urls', namespace='users')),
]

forums/urls.py
from django.conf.urls import url
from forums.views import (
    NewForumView, ForumIndexView, UpdateForumView,
    ChangeForumVisibilityView, ShowForumView
)


urlpatterns = [
    url(
        r'^$',
        ForumIndexView.as_view(),
        name='index'
    ),
    url(
        r'^new/$',
        NewForumView.as_view(),
        name='new'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        ShowForumView.as_view(),
        name='show'
    ),
    url(
        r'^(?P<slug>[\w-]+)/update/$',
        UpdateForumView.as_view(),
        name='update'
    ),
    url(
        r'^(?P<slug>[\w-]+)/visibility/$',
        ChangeForumVisibilityView.as_view(),
        name='visibility'
    ),
]

users/urls.py
from django.conf.urls import url
from users.views import (
    UserProfileView, UserLoginView, UserLogoutView, UserRegisterView
)


urlpatterns = [
    url(
        r'^login/$',
        UserLoginView.as_view(),
        name='login'
    ),
    url(
        r'^logout/$',
        UserLogoutView.as_view(),
        name='logout'
    ),
    url(
        r'^register/$',
        UserRegisterView.as_view(),
        name='register'
    ),
    url(
        r'^(?P<username>[\w-]+)/$',
        UserProfileView.as_view(),
        name='profile'
    ),
]

forums/models.py
from django.db import models
from django.utils.text import slugify


class VisibleManager(models.Manager):
    def get_queryset(self):
        return super(VisibleManager, self).get_queryset().filter(active=True)


class Forum(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.CharField(max_length=255)
    active = models.BooleanField(default=False)

    # Manager
    objects = models.Manager()
    visible = VisibleManager()

    # Foreign Keys
    moderators = models.ManyToManyField('users.User')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return u'%s' % self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Forum, self).save(*args, **kwargs)

    def threads(self):
        return self.thread_set.all()

    def thread_count(self):
        return self.thread_set.count()

    def moderator_list(self):
        return self.moderators.all()

forums/views.py
from django.core.urlresolvers import reverse
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from fora.mixins import LoginRequiredMixin
from forums.models import Forum


class ForumIndexView(ListView):
    context_object_name = 'forums'
    model = Forum


class NewForumView(LoginRequiredMixin, CreateView):
    model = Forum
    fields = ['name', 'description', 'active']

    def get_success_url(self):
        return reverse('forums:index')


class ForumMixin(object):

    def get_object(self):
        slug = self.kwargs.get('slug')
        try:
            return Forum.visible.get(slug=slug)
        except Forum.DoesNotExist:
            raise Http404('No Forum matches the given query.')


class UpdateForumView(LoginRequiredMixin, ForumMixin, UpdateView):
    context_object_name = 'forum'
    model = Forum
    fields = ['name', 'description']

    def get_success_url(self):
        return reverse('forums:index')


class ChangeForumVisibilityView(LoginRequiredMixin, UpdateView):
    context_object_name = 'forum'
    model = Forum
    fields = ['active']

    def get_success_url(self):
        return reverse('forums:index')


class ShowForumView(ForumMixin, DetailView):
    context_object_name = 'forum'
    model = Forum

forums/templates/forums/forum_detail.html
{% extends "base.html" %}

{% block content %}
<div class="forum-actions">
    <a href="{% url 'threads:new' %}" class="btn btn-success">New Thread</a>
    <a href="{% url 'forums:update' forum.slug %}" class="btn btn-secondary">Update</a>
    <a href="{% url 'forums:visibility' forum.slug %}" class="btn btn-secondary">Change Visibility</a>
</div>

<h2>{{ forum.name }}</h2>
<p class="description">{{ forum.description }}</p>

<table>
    <thead>
        <tr>
            <th>Subject</th>
            <th>Author</th>
            <th>Posts</th>
        </tr>
    </thead>
    <tbody>
    {% for thread in forum.threads %}
    <tr>
        <td><a href="{% url 'threads:show' thread.slug %}">{{ thread.subject }}</a></td>
        <td><a href="{% url 'users:profile' thread.author.username %}">{{ thread.author.username }}</td>
        <td>{{ thread.post_count }}</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="2" class="empty">No threads for this forum</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

forums/templates/forums/forum_form.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
        {% if forum %}
        <input type="submit" value="Update Forum" class="btn btn-success" />
        {% else %}
        <input type="submit" value="Create Forum" class="btn btn-success" />
        {% endif %}
        <a href="{% url 'forums:index' %}" class="btn btn-secondary">Cancel</a>
    </div>
</form>
{% endblock content %}

forums/templates/forums/forum_list.html
{% extends "base.html" %}

{% block content %}
<div class="forum-actions">
    <a href="{% url 'forums:new' %}" class="btn btn-success">New Forum</a>
</div>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Threads</th>
        </tr>
    </thead>
    <tbody>
    {% for forum in forums %}
    <tr>
        <td>
            <a href="{% url 'forums:show' forum.slug %}">{{ forum.name }}</a>
            {% if forum.moderator_list %}
            <div class="moderator-list">
                Moderators: 
                {% for moderator in forum.moderator_list %}
                    <a href="{% url 'users:profile' moderator.username %}">{{ moderator.username }}</a>
                {% endfor %}
            </div>
            {% endif %}
        </td>
        <td><span class="forum-description">{{ forum.description }}</span></td>
        <td>{{ forum.thread_count }}</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="2" class="empty">No forums found</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}